---
- name: Compile
  hosts: localhost
  vars:
    target: linux
    arch: amd64
  vars_files:
    - ../vars.yml
  gather_facts: False
  tasks:
    - include: templates/golang.yml

- name: Distribute prod
  hosts: prod
  vars:
    config_name: prod
  vars_files:
    - ../vars.yml
  gather_facts: True
  tasks:
    - include: templates/distribute.yml
    - include: templates/monit.yml
